import React from 'react';
import './Post.css'; 

const Create = ({ title, content, author, imageUrl }) => {
    return (
        <div className="post">
          <div className="post-header">
            <div className="author-profile">
              <img src='https://i.pinimg.com/originals/75/b3/d2/75b3d2176c3d9aadfb0a327614341d06.jpg' alt="Author Profile" className="author-image" />
              <p className="author-name">Timothee Chalamet</p>
            </div>
            <h2>The History of computer science</h2>
          </div>
          <img src='https://th.bing.com/th/id/OIP.12EF2ArY4N0MSM54laqd0gHaFG?rs=1&pid=ImgDetMain' alt="Post" className="post-image" />
          <p className="content">From 140 characters to a global conversation powerhouse, Twitter's growth has...</p>


          <div className="post-header2">
            <div className="author-profile2">
              <img src='https://th.bing.com/th/id/OIP.zFgAMsUYBFJsbh4iiBGfJQHaFj?w=228&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7' alt="Author Profile" className="author-image" />
              <p className="author-name">Elon Musk</p>
            </div>
            <h2>The power of AI is unpredictable</h2>
          </div>
          <img src='https://th.bing.com/th/id/OIP.HZ9w8YiyROitCGC910VXAQAAAA?w=277&h=184&c=7&r=0&o=5&dpr=1.3&pid=1.7' alt="Post" className="post-image" />
          <p className="content">Is there a word for that paranoid feeling you get when you think you may be reading/listening to something generated by a GPT?</p>

        </div>
      );
    };


export default Create;